---
name: CombatLogger
description: Simple plugin that allows you to punish combat loggers!
authors:
- Jack Noordhuis
- Fixfac
main: JackNoordhuis\CombatLogger\CombatLogger
version: 1.0.0-fixfac-guapo
api:
- 4.0.0
...
